# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Wujiarui Zheng
tagline:          'An EE Student'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Wujiarui Zheng'
  url:            https://www.zhengwujiarui.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ZWJRBEN
